# Generated by Django 3.1 on 2020-08-30 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('Lat', models.CharField(max_length=50)),
                ('Long', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=50)),
                ('Extra', models.CharField(max_length=100)),
                ('id_user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_data')),
            ],
        ),
    ]
